### ISSUE TITLE
campo Meta

### ISSUE THREAD

**Issue by Cae2** [bodedev/muambator-webhooks-python#2]
Oi pessoal! tenho 2 contas PRO no muambator e estou com um problema para fazer o plugin funcionar no meu WooCommerce.

Como o plugin do Woocommerce Correios dá conflito com outro plugin aqui (que é mais importante pra minha operação) acabei desativando ele e gostaria de usar o campo Metadata para que o plugin muambator pegasse nele os valores, mas ele não faz isso.

Estou desconfiado que o plugin de vocês só faz a varredura dentro do meta_data do pedido né? e esse outro plugin que tenho salva o Tracking dentro do meta_data do shipping_lines, tem como fazer algo para o plugin de voces fazer uma varredura dentro de "qualquer" meta_data digamos assim?

Hoje faço uma gambiarra aqui em Node + Angular, faço a consulta no API do Woocommerce e depois pego dentro do orders/shipping_lines/metadata/adsw_tip o tracking, salvo em CSV e importo lá no Muambator, maaaaas, seria bom já fazer isso pelo plugin de vocês hehe

um abraço e obrigado

**Comment by ironworld** [comment]
Oi amigo, bom dia!

Em primeiro lugar, perdão pelo tempo da demora desta resposta. Faz tempo que não passava por aqui para tirar as teias de aranha :).

O nosso plugin de WooCommerce está sendo reescrito do zero para facilitar a integração, seguindo as mesma linha do plugin do Mercado Livre e/ou do Shopify. 

Ele será lançado em Beta até o final deste mês. Você gostaria de fazer parte do nosso programa de Beta para testar a integração?

Um abração,

Baboo
