### ISSUE TITLE
api

### ISSUE THREAD

**Issue by raffacabofrio** [bodedev/muambator-webhooks-python#3]
Olá.

Sou desenvolvedor e assinei o plano pro hoje.

Minha necessidade acho que é bem simples. Gostaria de usar a api pra cadastrar objetos.

Como faço? Obrigado.

**Comment by ironworld** [comment]
Bom dia Raffaello, tudo bem com você?

O cadastro de pacotes via API é realizado através de um contato junto ao nosso site. Essa liberação tem custo e é indicada para clientes que tem um alto volume de cadastro de objetos. 

Um abração,

Baboo
